name: .NET Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Run localhost
      run: |
        pwd
        ls
        cd src/Chirp.Web
        dotnet run &
    - name: Install playwright
      run: |
        pwd
        ls
        cd test/PlaywrightTests
        pwsh bin/Debug/net8.0/playwright.ps1 install
        ps -aux
      
    - name: Test
      env:
        authentication_github_clientId: ${{ secrets.GITHUBCLIENTID }}
        authentication_github_clientSecret: ${{ secrets.GITHUBCLIENTSECRET }} 
      run: |
        dotnet test --no-build --verbosity normal
        


      
