name: .NET Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore

    - name: Reset database
      run: |
        dotnet tool install --global dotnet-ef --version 8
        dotnet ef database drop --force
      working-directory: ./src/Chirp.Razor
    
    - name: Initialize database
      run: |
        dotnet ef migrations add InitialDBSchema
        dotnet ef database update
      working-directory: ./src/Chirp.Razor
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
