name: release.yml
on:
  push:
    tags:
      - "v*.*.*"
        
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Initialise database
        run: |
          sqlite3 /tmp/chirp.db < data/schema.sql
          sqlite3 /tmp/chirp.db < data/dump.sql
        working-directory: ./src/Chirp.Razor

      - name: Test
        run: dotnet test --no-build --verbosity normal
          
  # Publish for Linux
      - name: Publish Linux
        run: dotnet publish src/Chirp.Razor/Chirp.Razor.csproj -r linux-x64 -o publish/linux-x64 --no-self-contained 
          
# Zip Linux artifacts
      - name: Zip Linux Artifacts
        run: zip -r Chirp_Razor_linux-x64.zip publish/linux-x64

# Publish for Windows
      - name: Publish Windows
        run: dotnet publish src/Chirp.Razor/Chirp.Razor.csproj -r win-x64 -o publish/win-x64 --no-self-contained

# Zip Windows artifacts
      - name: Zip Windows Artifacts
        run: zip -r Chirp_Razpr_win-x64.zip publish/win-x64

# Publish for MacOS x64
      - name: Publish MacOS x64
        run: dotnet publish src/Chirp.Razor/Chirp.Razor.csproj -r osx-x64 -o publish/osx-x64 --no-self-contained

# Zip MacOS x64 artifacts
      - name: Zip MacOS x64 Artifacts
        run: zip -r Chirp_Razor_osx-x64.zip publish/osx-x64

# Publish for MacOS ARM
      - name: Publish MacOS ARM
        run: dotnet publish src/Chirp.Razor/Chirp.Razor.csproj -r osx-arm64 -o publish/osx-arm64

# Zip MacOS ARM artifacts
      - name: Zip MacOS ARM Artifacts
        run: zip -r Chirp_Razor_osx-arm64.zip publish/osx-arm64
        
      - name: Create Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
              Chirp_Razor_linux-x64.zip
              Chirp_Razor_win-x64.zip
              Chirp_Razor_osx-x64.zip
              Chirp_Razor_osx-arm64.zip
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}