name: release.yml

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
         dotnet-version: 7.0.x
        
      - name: Restore dependencies
        run: dotnet restore
        
      - name: Build
        run: dotnet build --no-restore
        
      - name: Test
        run: dotnet test --no-build --verbosity normal
        
      - name: Publish
        run : dotnet publish
        
      - name: Zip Chirp
        run : zip -r Chirp.zip "src/Chirp.CLI.Client/bin/Debug/net7.0/publish/"
        
      - name: Zip SimpleDB
        run : zip -r SimpleDB.zip "src/SimpleDB/bin/Debug/net7.0/publish/"
  
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
            files: |
              Chirp.zip
              SimpleDB.zip
        